PREFIX rdf: 		<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: 		<http://www.w3.org/2002/07/owl#>
PREFIX xsd: 		<http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: 		<http://www.w3.org/2000/01/rdf-schema#>
PREFIX cricket: 	<http://www.semanticweb.org/admin/ontologies/2015/2/11/cricket#>
SELECT ?sub ?PlayerName ?PlayerType ?Team
WHERE { 
?sub rdf:type cricket:Player .
?sub cricket:PlayerName ?PlayerName .
?sub cricket:PlayerType ?PlayerType .
?sub cricket:isPlayerOf ?Team .
FILTER regex(?PlayerType,'^Allrounder','i')
} 
ORDER BY ?Team
